// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFLTeams.Models;

namespace NFLTeamsSessions.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20230315100626_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NFLTeamsSessions.Models.Conference", b =>
                {
                    b.Property<string>("ConferenceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConferenceID");

                    b.ToTable("Conferences");

                    b.HasData(
                        new
                        {
                            ConferenceID = "afc",
                            Name = "AFC"
                        },
                        new
                        {
                            ConferenceID = "nfc",
                            Name = "NFC"
                        });
                });

            modelBuilder.Entity("NFLTeamsSessions.Models.Division", b =>
                {
                    b.Property<string>("DivisionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DivisionID");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            DivisionID = "north",
                            Name = "North"
                        },
                        new
                        {
                            DivisionID = "south",
                            Name = "South"
                        },
                        new
                        {
                            DivisionID = "east",
                            Name = "East"
                        },
                        new
                        {
                            DivisionID = "west",
                            Name = "West"
                        });
                });

            modelBuilder.Entity("NFLTeamsSessions.Models.Team", b =>
                {
                    b.Property<string>("TeamID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConferenceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DivisionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.HasIndex("ConferenceID");

                    b.HasIndex("DivisionID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = "ari",
                            ConferenceID = "nfc",
                            DivisionID = "west",
                            Name = "Arizona Cardinals"
                        },
                        new
                        {
                            TeamID = "atl",
                            ConferenceID = "nfc",
                            DivisionID = "south",
                            Name = "Atlanta Falcons"
                        },
                        new
                        {
                            TeamID = "bal",
                            ConferenceID = "afc",
                            DivisionID = "north",
                            Name = "Baltimore Ravens"
                        },
                        new
                        {
                            TeamID = "buf",
                            ConferenceID = "afc",
                            DivisionID = "east",
                            Name = "Buffalo Bills"
                        },
                        new
                        {
                            TeamID = "car",
                            ConferenceID = "nfc",
                            DivisionID = "south",
                            Name = "Carolina Panthers"
                        },
                        new
                        {
                            TeamID = "chi",
                            ConferenceID = "nfc",
                            DivisionID = "north",
                            Name = "Chicago Bears"
                        },
                        new
                        {
                            TeamID = "cin",
                            ConferenceID = "afc",
                            DivisionID = "north",
                            Name = "Cincinnati Bengals"
                        },
                        new
                        {
                            TeamID = "cle",
                            ConferenceID = "afc",
                            DivisionID = "north",
                            Name = "Cleveland Browns"
                        },
                        new
                        {
                            TeamID = "dal",
                            ConferenceID = "nfc",
                            DivisionID = "east",
                            Name = "Dallas Cowboys"
                        },
                        new
                        {
                            TeamID = "den",
                            ConferenceID = "afc",
                            DivisionID = "west",
                            Name = "Denver Broncos"
                        },
                        new
                        {
                            TeamID = "det",
                            ConferenceID = "nfc",
                            DivisionID = "north",
                            Name = "Detroit Lions"
                        },
                        new
                        {
                            TeamID = "gb",
                            ConferenceID = "nfc",
                            DivisionID = "north",
                            Name = "Green Bay Packers"
                        },
                        new
                        {
                            TeamID = "hou",
                            ConferenceID = "afc",
                            DivisionID = "south",
                            Name = "Houston Texans"
                        },
                        new
                        {
                            TeamID = "ind",
                            ConferenceID = "afc",
                            DivisionID = "south",
                            Name = "Indianapolis Colts"
                        },
                        new
                        {
                            TeamID = "jax",
                            ConferenceID = "afc",
                            DivisionID = "south",
                            Name = "Jacksonville Jaguars"
                        },
                        new
                        {
                            TeamID = "kc",
                            ConferenceID = "afc",
                            DivisionID = "west",
                            Name = "Kansas City Chiefs"
                        },
                        new
                        {
                            TeamID = "lac",
                            ConferenceID = "afc",
                            DivisionID = "west",
                            Name = "Los Angeles Chargers"
                        },
                        new
                        {
                            TeamID = "lar",
                            ConferenceID = "nfc",
                            DivisionID = "west",
                            Name = "Los Angeles Rams"
                        },
                        new
                        {
                            TeamID = "mia",
                            ConferenceID = "afc",
                            DivisionID = "east",
                            Name = "Miami Dolphins"
                        },
                        new
                        {
                            TeamID = "min",
                            ConferenceID = "nfc",
                            DivisionID = "north",
                            Name = "Minnesota Vikings"
                        },
                        new
                        {
                            TeamID = "ne",
                            ConferenceID = "afc",
                            DivisionID = "east",
                            Name = "New England Patriots"
                        },
                        new
                        {
                            TeamID = "no",
                            ConferenceID = "nfc",
                            DivisionID = "south",
                            Name = "New Orleans Saints"
                        },
                        new
                        {
                            TeamID = "nyg",
                            ConferenceID = "nfc",
                            DivisionID = "east",
                            Name = "New York Giants"
                        },
                        new
                        {
                            TeamID = "nyj",
                            ConferenceID = "afc",
                            DivisionID = "east",
                            Name = "New York Jets"
                        },
                        new
                        {
                            TeamID = "oak",
                            ConferenceID = "afc",
                            DivisionID = "west",
                            Name = "Oakland Raiders"
                        },
                        new
                        {
                            TeamID = "phi",
                            ConferenceID = "nfc",
                            DivisionID = "east",
                            Name = "Philadelphia Eagles"
                        },
                        new
                        {
                            TeamID = "pit",
                            ConferenceID = "afc",
                            DivisionID = "north",
                            Name = "Pittsburgh Steelers"
                        },
                        new
                        {
                            TeamID = "sea",
                            ConferenceID = "nfc",
                            DivisionID = "west",
                            Name = "Seattle Seahawks"
                        },
                        new
                        {
                            TeamID = "sf",
                            ConferenceID = "nfc",
                            DivisionID = "west",
                            Name = "San Francisco 49ers"
                        },
                        new
                        {
                            TeamID = "tb",
                            ConferenceID = "nfc",
                            DivisionID = "south",
                            Name = "Tampa Bay Buccaneers"
                        },
                        new
                        {
                            TeamID = "ten",
                            ConferenceID = "afc",
                            DivisionID = "south",
                            Name = "Tennessee Titans"
                        },
                        new
                        {
                            TeamID = "was",
                            ConferenceID = "nfc",
                            DivisionID = "east",
                            Name = "Washington Redskins"
                        });
                });

            modelBuilder.Entity("NFLTeamsSessions.Models.Team", b =>
                {
                    b.HasOne("NFLTeamsSessions.Models.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceID");

                    b.HasOne("NFLTeamsSessions.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionID");

                    b.Navigation("Conference");

                    b.Navigation("Division");
                });
#pragma warning restore 612, 618
        }
    }
}
